// <auto-generated />
namespace ClientOrganizer.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Changefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changefield));
        
        string IMigrationMetadata.Id
        {
            get { return "202102142251389_Changefield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
